application:
  image: yii2/code
  volumes:
    - .:/var/www/yii2
  tty: true

db:
  image: mysql
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: mysqlroot
    MYSQL_DATABASE: yii2
    MYSQL_USER: admin
    MYSQL_PASSWORD: root
  volumes:
    - /home/mysql2:/var/lib/mysql

php:
  image: yii2/php-fpm
  expose:
    - 9000:9000
  volumes_from:
    - application
  links:
    - db
  
nginx:
  image: yii2/nginx
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - application
  volumes:
    - runtime/logs/nginx/:/var/log/nginx
